class SearchValidator < ActiveModel::Validator 
    def validate(record)
        scanner = SkyScanner.new
        result = scanner.find_airports(record.package_data)
        # This is the response generated by the SkyScanner API when invalid parameters (or no parameters) are passed in
        record.errors.add(:base, "data not found via API") if result.code == "404" || result.code == "400"
    end
end